name: E2E Test with Cypress
'on': pull_request
jobs:
  cypress:
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Cache Firebase Emulators'
        uses: actions/cache@v2
        with:
          path: $HOME/.cache/firebase
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/*.{jar,zip}') }}

      - name: Build Cloud Functions
        run: |
          cd functions
          echo $BASE64_FIREBASE_ADMIN_CONFIG | base64 --decode > ./src/code-base-firebase-adminsdk.json
          yarn
          yarn build
        env:
          BASE64_FIREBASE_ADMIN_CONFIG: ${{ secrets.BASE64_FIREBASE_ADMIN_CONFIG }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start, yarn emulate --project ${{ secrets.REACT_APP_PROJECT_ID }}
          wait-on:  http://localhost:3000, http://localhost:4000
          wait-on-timeout: 120
          record: true
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_FIREBASE_EMULATOR: true
